# Generated by Django 2.2.11 on 2020-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='html_text',
            field=models.FileField(default='ANONYMOUS', upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image_link',
            field=models.TextField(default='ANONYMOUS'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='ANONYMOUS', max_length=100),
        ),
    ]
